### ISSUE TITLE
It's a great work of fashion retrieval, and could you provided the pretrained model?

### ISSUE THREAD

**Issue by ghost** [birdortyedi/image-retrieval-with-capsules#2]
I will cherish your help!

**Comment by ghost** [comment]
I don't know how to organize the deepfashion dataset in your repo, could you give a brief introduction for me?

**Comment by birdortyedi** [comment]
> I will cherish your help!

Thanks for your great comments, the pretrained model can be found in this link: https://we.tl/t-AMHjQp2dny
For organizing the dataset part, I need more time to explain. You may look at this blog post containing preliminary work for this task. https://medium.com/@birdortyedi_23820/deep-learning-lab-episode-4-deep-fashion-2df9e15a63e1

**Comment by ghost** [comment]
> > I will cherish your help!
> 
> Thanks for your great comments, the pretrained model can be found in this link: https://we.tl/t-AMHjQp2dny
> For organizing the dataset part, I need more time to explain. You may look at this blog post containing preliminary work for this task. https://medium.com/@birdortyedi_23820/deep-learning-lab-episode-4-deep-fashion-2df9e15a63e1

Thank you for your reply, I have also known the organization of your data from your code.

**Comment by akshathvarugeese** [comment]
> > I will cherish your help!
> 
> Thanks for your great comments, the pretrained model can be found in this link: https://we.tl/t-AMHjQp2dny
> For organizing the dataset part, I need more time to explain. You may look at this blog post containing preliminary work for this task. https://medium.com/@birdortyedi_23820/deep-learning-lab-episode-4-deep-fashion-2df9e15a63e1

The link to the pre-trained model seems to be expired, can you please share it with me too?

**Comment by ghost** [comment]
> > > I will cherish your help!
> > 
> > 
> > Thanks for your great comments, the pretrained model can be found in this link: https://we.tl/t-AMHjQp2dny
> > For organizing the dataset part, I need more time to explain. You may look at this blog post containing preliminary work for this task. https://medium.com/@birdortyedi_23820/deep-learning-lab-episode-4-deep-fashion-2df9e15a63e1
> 
> The link to the pre-trained model seems to be expired, can you please share it with me too?

I haven't download the pre-trained model in time, but I use his codes to train a new model several weeks ago, the model is here https://drive.google.com/file/d/1vdmdoQ4biqJFjp7GIa1IWrlx1z8JWe-t/view?usp=sharing

**Comment by akshathvarugeese** [comment]
> > > > I will cherish your help!
> > > 
> > > 
> > > Thanks for your great comments, the pretrained model can be found in this link: https://we.tl/t-AMHjQp2dny
> > > For organizing the dataset part, I need more time to explain. You may look at this blog post containing preliminary work for this task. https://medium.com/@birdortyedi_23820/deep-learning-lab-episode-4-deep-fashion-2df9e15a63e1
> > 
> > 
> > The link to the pre-trained model seems to be expired, can you please share it with me too?
> 
> I haven't download the pre-trained model in time, but I use his codes to train a new model several weeks ago, the model is here https://drive.google.com/file/d/1vdmdoQ4biqJFjp7GIa1IWrlx1z8JWe-t/view?usp=sharing

Thanks for the quick response, I will experiment with your model. Did you achieve the same/close results as the authors mentioned in the paper?
